### ISSUE TITLE
Vertaispalaute 2

### ISSUE THREAD

**Issue by Eoyie** [t0ffe/tkt-tsoha#1]
Ohjelmaa oli hiukan vaikea testata, sillä en saanut rekisteröintiä toimimaan. En oikein README:stä saanut selville, että onko ongelma minun puolella vai ei (En ollut varma oliko README siis nykyinen tilanne vai yleinen tavoite ominaisuuksista), mutta koodissa näytti lukevan “#TODO implement registering” joten oletan, että asia on tiedossa. Kurkkasin kuitenkin koodia muuttamalla niitä sivuja mihin en pääse käsiksi ja ne näyttävät ihan järkeviltä, vaikka en sinäänsä pysty tehdä niillä mitään.

Myös committien koot näyttävät hyvältä ja koodi siistiä (tosin jotkin rivit ovat kovin pitkiä. Esim. VS Coden rulerit auttavat visuaalisoimaan rivien pituudet). Erityisesti pidän tietokannan rakenteesta ja tätä esittämästä kuvasta! Ehkä voi harkita tietokantaan UNIQUE sääntöä esim. käyttäjille, sillä saattaa mennä sen kanssa sekaisin (en tosin voinut testata).

Mitä suosittelisin siis vielä arvostelu sivun perusteella huomioimaan ovat:
Toimivuus/testattavuus
Ulkoasu viimeisteltyä
Koodi tiivistä (pituus)

Yleisesti siis näyttää siltä, että sovellus on hyvässä mallissa, kunhan voisi luoda käyttäjän. En keksi muuta mainittavaa :)

**Comment by t0ffe** [comment]
latest commit ([983206d](https://github.com/t0ffe/tkt-tsoha/commit/983206d819409c20d4c0ec207c7ec6704696bba0)) should fix registering not working
